"""empty message

Revision ID: 657ff943c85d
Revises: 3fc2a567e75c
Create Date: 2021-06-24 13:10:02.627152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657ff943c85d'
down_revision = '3fc2a567e75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
